version: "3.8"

services:
  backend:
    build: ./backend
    container_name: fusionpact-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app/data:/app/data
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: fusionpact-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: fusionpact-prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus        # <-- Persistent data for metrics
    ports:
      - "9090:9090"
    depends_on:
      - backend
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: fusionpact-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana      # <-- Persistent data for dashboards, alerts
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  prometheus-data:
  grafana-data:
